import type { Generator } from '../types/game'

export const generators: Generator[] = [
  {
    id: 'vowel-press',
    name: 'Vowel Press',
    description: 'Stamps vowels into ledgers for $2/s.',
    baseCost: 480,
    costGrowth: 1.55,
    baseIncome: 2,
    tier: 1,
  },
  {
    id: 'consonant-cascade',
    name: 'Consonant Cascade',
    description: 'Sorts consonants into bins for $5/s.',
    baseCost: 1100,
    costGrowth: 1.58,
    baseIncome: 5,
    tier: 2,
    requires: 'vowel-press',
  },
  {
    id: 'digraph-forge',
    name: 'Digraph Forge',
    description: 'Fuses double letters for $10/s.',
    baseCost: 2200,
    costGrowth: 1.62,
    baseIncome: 10,
    tier: 3,
    requires: 'consonant-cascade',
  },
  {
    id: 'homophone-kiln',
    name: 'Homophone Kiln',
    description: 'Tunes homophones for $18/s.',
    baseCost: 3800,
    costGrowth: 1.65,
    baseIncome: 18,
    tier: 4,
    requires: 'digraph-forge',
  },
  {
    id: 'lexicon-observatory',
    name: 'Lexicon Observatory',
    description: 'Charts morphemes for $32/s.',
    baseCost: 6200,
    costGrowth: 1.7,
    baseIncome: 32,
    tier: 5,
    requires: 'homophone-kiln',
  },
]
