import type { Upgrade } from '../types/game'

export const upgrades: Upgrade[] = [
  {
    id: 'flip-accelerators',
    name: 'Flip Accelerators',
    description: 'Tiles resolve 150ms faster per tier.',
    baseCost: 180,
    costGrowth: 1.5,
    maxLevel: 4,
    tier: 1,
    wordCost: 4,
    effect: { flipDurationDelta: -150 },
  },
  {
    id: 'mint-overclock',
    name: 'Mint Overclock',
    description: 'Every tier injects +6 payout to each guess.',
    baseCost: 220,
    costGrowth: 1.5,
    maxLevel: null,
    tier: 1,
    wordCost: 6,
    effect: { payoutBonus: 6 },
  },
  {
    id: 'length-6',
    name: 'Six-Letter Archives',
    description: 'Unlocks 6-letter words for prestigious payouts.',
    baseCost: 620,
    costGrowth: 1,
    maxLevel: 1,
    tier: 2,
    wordCost: 14,
    effect: { unlockLength: 6 },
  },
  {
    id: 'length-7',
    name: 'Seven-Letter Vaults',
    description: 'Opens the vault for 7-letter monsters.',
    baseCost: 2100,
    costGrowth: 1,
    maxLevel: 1,
    requires: 'length-6',
    tier: 3,
    wordCost: 38,
    effect: { unlockLength: 7 },
  },
  {
    id: 'thermal-visor',
    name: 'Thermal Visor',
    description: 'Swap Wordle colors for hot/cold heat maps.',
    baseCost: 360,
    costGrowth: 1,
    maxLevel: 1,
    tier: 2,
    wordCost: 12,
    effect: { showHotCold: true },
  },
  {
    id: 'precision-drills',
    name: 'Precision Drills',
    description: 'Tiered drills add +3 payout and scale forever.',
    baseCost: 360,
    costGrowth: 1.45,
    maxLevel: null,
    tier: 2,
    wordCost: 14,
    effect: { payoutBonus: 3 },
  },
  {
    id: 'phoneme-consortium',
    name: 'Phoneme Consortium',
    description: 'Foundry output climbs +10% idle cash per tier.',
    baseCost: 580,
    costGrowth: 1.55,
    maxLevel: 5,
    tier: 2,
    wordCost: 16,
    effect: { idleMultiplier: 1.1 },
  },
  {
    id: 'lexicon-contracts',
    name: 'Lexicon Contracts',
    description: 'Each solved word yields +1 extra word per tier.',
    baseCost: 780,
    costGrowth: 1.5,
    maxLevel: 2,
    tier: 2,
    wordCost: 18,
    effect: { wordBonus: 1 },
  },
  {
    id: 'extra-guess',
    name: 'Deep Breath',
    description: 'Each tier grants +1 guess buffer.',
    baseCost: 420,
    costGrowth: 1.75,
    maxLevel: 2,
    tier: 3,
    wordCost: 20,
    effect: { guessLimit: 1 },
  },
  {
    id: 'hard-mode',
    name: 'Hard Mode Overdrive',
    description: 'Unlocks brutal scoring and doubles minted money.',
    baseCost: 1500,
    costGrowth: 1,
    maxLevel: 1,
    tier: 3,
    wordCost: 34,
    requires: 'precision-drills',
    effect: { payoutMultiplier: 2 },
  },
  {
    id: 'lexeme-trust',
    name: 'Lexeme Trust',
    description: 'Compounds idle output by +15% per tier.',
    baseCost: 1500,
    costGrowth: 1.6,
    maxLevel: 4,
    tier: 3,
    wordCost: 26,
    requires: 'phoneme-consortium',
    effect: { idleMultiplier: 1.15 },
  },
  {
    id: 'etymology-bonds',
    name: 'Etymology Bonds',
    description: 'Each solve inks another word contract.',
    baseCost: 1300,
    costGrowth: 1.65,
    maxLevel: 3,
    tier: 3,
    wordCost: 24,
    requires: 'lexicon-contracts',
    effect: { wordBonus: 1 },
  },
  {
    id: 'semantic-overseer',
    name: 'Semantic Overseer',
    description: 'Global idle output surges by +20% per tier.',
    baseCost: 3200,
    costGrowth: 1.65,
    maxLevel: 3,
    tier: 4,
    wordCost: 40,
    requires: 'lexeme-trust',
    effect: { idleMultiplier: 1.2 },
  },
]
