import type { Upgrade } from '../types/game'

export const upgrades: Upgrade[] = [
  {
    id: 'length-6',
    name: 'Six-Letter Archives',
    description: 'Unlocks 6-letter words for prestigious payouts.',
    baseCost: 420,
    costGrowth: 1,
    maxLevel: 1,
    tier: 2,
    wordCost: 10,
    effect: { unlockLength: 6 },
  },
  {
    id: 'length-7',
    name: 'Seven-Letter Vaults',
    description: 'Opens the vault for 7-letter monsters.',
    baseCost: 1200,
    costGrowth: 1,
    maxLevel: 1,
    requires: 'length-6',
    tier: 3,
    wordCost: 28,
    effect: { unlockLength: 7 },
  },
  {
    id: 'thermal-visor',
    name: 'Thermal Visor',
    description: 'Swap Wordle colors for hot/cold heat maps.',
    baseCost: 280,
    costGrowth: 1,
    maxLevel: 1,
    tier: 2,
    wordCost: 6,
    effect: { showHotCold: true },
  },
  {
    id: 'mint-overclock',
    name: 'Mint Overclock',
    description: 'Every tier injects +6 payout to each guess.',
    baseCost: 160,
    costGrowth: 1.45,
    maxLevel: null,
    tier: 1,
    wordCost: 4,
    effect: { payoutBonus: 6 },
  },
  {
    id: 'precision-drills',
    name: 'Precision Drills',
    description: 'Tiered drills add +3 payout and scale forever.',
    baseCost: 240,
    costGrowth: 1.4,
    maxLevel: null,
    tier: 2,
    wordCost: 8,
    effect: { payoutBonus: 3 },
  },
  {
    id: 'extra-guess',
    name: 'Deep Breath',
    description: 'Each tier grants +1 guess buffer.',
    baseCost: 210,
    costGrowth: 1.7,
    maxLevel: 3,
    tier: 3,
    wordCost: 12,
    effect: { guessLimit: 1 },
  },
  {
    id: 'hard-mode',
    name: 'Hard Mode Overdrive',
    description: 'Unlocks brutal scoring and doubles minted money.',
    baseCost: 940,
    costGrowth: 1,
    maxLevel: 1,
    tier: 3,
    wordCost: 24,
    requires: 'precision-drills',
    effect: { payoutMultiplier: 2 },
  },
]
